# Playing with matrices
(and if you get the subliminal message about abstractions, we'll be thrilled!)

Julia is a dynamic language.  You don't need type declarations, and can change variable types dynamically and interactively.

For working with simple numbers, arrays, and strings, its syntax is *superficially* similar to Matlab, Python, and other popular languages.

In order to execute the `In` cells, select the cell and press `Shift-Enter`, or press the `Play` button above. To run the entire notebook, navigate to the `Cell` menu and then `Run All`.

# We tell beginners, you don't need types!

In [1]:
typeof(1.0)

Float64

In [2]:
typeof(1)

Int64

In [3]:
S = "Hello Julia Clsas"
typeof(S)

String

In [4]:
#  Exercise fix my spelling in the cell above
S

"Hello Julia Clsas"

# Now forget all that (for now): Julia is not so different from your favorite dynamic language

In [5]:
1 + 1  # shift + enter to run

2

In [6]:
A = rand(5, 5)

5×5 Array{Float64,2}:
 0.750034   0.07053    0.706369  0.124092  0.511954
 0.872182   0.49595    0.015546  0.501883  0.519616
 0.0511668  0.196402   0.311318  0.668024  0.459664
 0.610053   0.211064   0.408385  0.690457  0.146332
 0.7398     0.0536768  0.829703  0.279061  0.315199

In [7]:
A = SymTridiagonal(rand(6), rand(5))

6×6 SymTridiagonal{Float64}:
 0.951003  0.980529   ⋅         ⋅          ⋅         ⋅      
 0.980529  0.819793  0.997924   ⋅          ⋅         ⋅      
  ⋅        0.997924  0.402079  0.484407    ⋅         ⋅      
  ⋅         ⋅        0.484407  0.0432339  0.173544   ⋅      
  ⋅         ⋅         ⋅        0.173544   0.542394  0.852725
  ⋅         ⋅         ⋅         ⋅         0.852725  0.155613

In [8]:
b = rand(6)
A \ b

6-element Array{Float64,1}:
  58.1438 
 -55.4231 
 -11.4515 
 125.405  
   5.85443
 -28.7292 

In [9]:
A = fill(3.15, 5, 5) # Fill a 5x5 array with 0's

5×5 Array{Float64,2}:
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15

# Let's create some addition tables

First let's use a nested for loop to fill in a matrix that's initially zero:

In [10]:
A = zeros(5, 5)

for i=1:5
    for j=1:5
        A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
    end
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

We can abbreviate this using a double `for` loop:

In [11]:
for i=1:5, j=1:5
   A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

The Julia way would be to use a so-called **array comprehension**:

In [12]:
[i+j for i=1:5, j=1:5]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

**Explore**: What does the following do? 

In [13]:
[i*100 for i in (1:7).^2]

7-element Array{Int64,1}:
  100
  400
  900
 1600
 2500
 3600
 4900

**Explore**: What does the following do? 

In [14]:
sort(unique(x^2 + y^2 for x in 1:5, y in 1:5))  # The inner parentheses define a **generator**

15-element Array{Any,1}:
  2
  5
  8
 10
 13
 17
 18
 20
 25
 26
 29
 32
 34
 41
 50

Suppose we want to see $n \times n$ multiplication tables for $n=1,2,3,4,5$:

In [15]:
for n = 1:5
    display([i*j for i=1:n, j=1:n])
end

1×1 Array{Int64,2}:
 1

2×2 Array{Int64,2}:
 1  2
 2  4

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

# `Interact.jl` is a Julia *package* for interacting with data

It's way more fun to **interact** with our data.
We install the `Interact.jl` package as follows; this needs to be executed only once for any given Julia installation:

In [16]:
Pkg.add("Interact")

INFO: Nothing to be done
INFO: METADATA is out-of-date — you may not have the latest version of Interact
INFO: Use `Pkg.update()` to get the latest versions of your packages


Now we load the package with the following `using` command, in each Julia session:

In [17]:
using Interact

The package contains a `@manipulate` macro, that is wrapped around a `for` loop:

In [18]:
@manipulate for n = 1:1000
    n
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(500, nactions=1),"n",500,"500",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(306=>"306",29=>"29",74=>"74",905=>"905",176=>"176",892=>"892",285=>"285",318=>"318",873=>"873",975=>"975"…)),Any[],Any[],true,"horizontal")

500

In [19]:
@manipulate for n=1:20
    [i*j for i=1:n, j=1:n]
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(10, nactions=1),"n",10,"10",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(18=>"18",2=>"2",16=>"16",11=>"11",7=>"7",9=>"9",10=>"10",19=>"19",17=>"17",8=>"8"…)),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

We use a double `for` loop to get a double slider!

In [20]:
@manipulate for n=3:10, i=1:9
   A = fill(0, n, n)
   A[1:3, 1:3] = i    # fill a sub-block
A
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(6, nactions=1),"n",6,"6",Interact.OptionDict(DataStructures.OrderedDict("3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10),Dict(7=>"7",4=>"4",9=>"9",10=>"10",3=>"3",5=>"5",8=>"8",6=>"6")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(5, nactions=1),"i",5,"5",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9),Dict(7=>"7",4=>"4",9=>"9",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

6×6 Array{Int64,2}:
 5  5  5  0  0  0
 5  5  5  0  0  0
 5  5  5  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

# Functions

Julia is built around functions: all "commands" or "operations" in Julia are functions:

In [21]:
# verbose form:
function f(x)
    x^2
end

# one-line form:
f2(x) = x^2

# anonymous form:
f3 = x -> x^2;

In [22]:
f(10)

100

Functions just work, as long as they make sense:

In [23]:
f(rand(3, 3))

3×3 Array{Float64,2}:
 0.677224  0.106166  0.75396 
 0.481557  0.449098  0.663103
 0.820264  0.118254  1.31578 

In [24]:
function f(x, power=2) # default argument
    x^power
end

f (generic function with 2 methods)

In [25]:
f(7)

49

In [26]:
f(10,3)

1000

Let's define a function to insert a block in a matrix:

In [27]:
function insert_block(A, i, j, what=7)
    B = A[:,:]        # B is a copy of A       
    B[i:i+2, j:j+2] = fill(what, 3, 3)
    
    return B          # the `return` keyword is optional
end

insert_block (generic function with 2 methods)

In [28]:
A = fill(0, 9, 9)
insert_block(A, 3, 5)  # this returns the new matrix

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [29]:
A = fill(0, 9, 9)
insert_block(A, 3, 5, 2)  # Use 2 instead of 7

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

We can move the block around:

In [30]:
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

# Strings

Julia can manipulate strings easily:

In [31]:
S = "Hello"

"Hello"

In [32]:
replace(S, "H", "J")

"Jello"

In [33]:
a = 3

3

In [34]:
string(S, " ", S, " ", "Julia; a = ", a)  # build a string by concatenating things

"Hello Hello Julia; a = 3"

More about strings: <a href="http://docs.julialang.org/en/stable/manual/strings/"> Julia Doc on Strings </a>

Functions in Julia try to be **generic**, i.e. to work with as many kinds of object as possible:

In [35]:
A = fill("Julia", 5, 5)

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

Julia allows us to display objects in different ways. For example, the following code displays a matrix of strings
in the notebook using an HTML representation:

In [36]:
function Base.show{T<:String}(io::IO, ::MIME"text/html", M::Matrix{T}) 
    max_length = maximum(length.(M))
    dv="<div style='display:flex;flex-direction:row'>"
    print(io, dv*join([join("<div style='width:40px; text-align:center'>".*M[i,:].*"</div>", " ") for i in 1:size(M, 1)]
            , "</div>$dv")*"</div>")
end

In [37]:
A

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

In [38]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

Let's use the **same code**, but now with strings:

In [39]:
A = fill("Julia", 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "[FUN]")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [40]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "π")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [41]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "♡")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [42]:
airplane = "✈"
alien = "👽"
rand([airplane, alien], 5, 5)

5×5 Array{String,2}:
 "✈"  "✈"  "👽"  "✈"  "✈"
 "✈"  "👽"  "👽"  "👽"  "👽"
 "👽"  "✈"  "✈"  "👽"  "👽"
 "✈"  "👽"  "✈"  "👽"  "✈"
 "✈"  "👽"  "👽"  "✈"  "✈"

In [43]:
A = fill(airplane, 9, 9)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, alien)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

9×9 Array{String,2}:
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"

# Colors

The `Colors` package provides objects representing colours:

In [44]:
using Colors

In [45]:
distinguishable_colors(12)

In [46]:
@manipulate for n = 1:80
    distinguishable_colors(n)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(40, nactions=1),"n",40,"40",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(68=>"68",2=>"2",11=>"11",39=>"39",46=>"46",25=>"25",55=>"55",42=>"42",29=>"29",58=>"58"…)),Any[],Any[],true,"horizontal")

In [47]:
colors = distinguishable_colors(100)


In [48]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

What happens if we use colours instead?

In [49]:
A = fill(colors[1], 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, colors[4])
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

In [50]:
# Exercise: Create Tetris Pieces, have them fall from the top