# Playing with matrices
(and if you get the subliminal message about abstractions, we'll be thrilled!)

Julia is a dynamic language.  You don't need type declarations, and can change variable types dynamically and interactively.

For working with simple numbers, arrays, and strings, its syntax is *superficially* similar to Matlab, Python, and other popular languages.

In order to execute the `In` cells, select the cell and press `Shift-Enter`, or press the `Play` button above. To run the entire notebook, navigate to the `Cell` menu and then `Run All`.

# We tell beginners, you don't need types!

In [ ]:
typeof(1.0)

In [ ]:
typeof(1)

In [ ]:
S = "Hello Julia Clsas"
typeof(S)

In [ ]:
#  Exercise fix my spelling in the cell above
S

# Now forget all that (for now): Julia is not so different from your favorite dynamic language

In [ ]:
1 + 1  # shift + enter to run

In [ ]:
A = rand(5, 5)

In [ ]:
A = SymTridiagonal(rand(6), rand(5))

In [ ]:
b = rand(6)
A \ b

In [ ]:
A = fill(3.15, 5, 5) # Fill a 5x5 array with 0's

# Let's create some addition tables

First let's use a nested for loop to fill in a matrix that's initially zero:

In [ ]:
A = zeros(5, 5)

for i=1:5
    for j=1:5
        A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
    end
end

A

We can abbreviate this using a double `for` loop:

In [ ]:
for i=1:5, j=1:5
   A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
end

A

The Julia way would be to use a so-called **array comprehension**:

In [ ]:
[i+j for i=1:5, j=1:5]

**Explore**: What does the following do? 

In [ ]:
[i*100 for i in (1:7).^2]

**Explore**: What does the following do? 

In [ ]:
sort(unique(x^2 + y^2 for x in 1:5, y in 1:5))  # The inner parentheses define a **generator**

Suppose we want to see $n \times n$ multiplication tables for $n=1,2,3,4,5$:

In [ ]:
for n = 1:5
    display([i*j for i=1:n, j=1:n])
end

# `Interact.jl` is a Julia *package* for interacting with data

It's way more fun to **interact** with our data.
We install the `Interact.jl` package as follows; this needs to be executed only once for any given Julia installation:

In [ ]:
Pkg.add("Interact")

Now we load the package with the following `using` command, in each Julia session:

In [13]:
using Interact

The package contains a `@manipulate` macro, that is wrapped around a `for` loop:

In [ ]:
@manipulate for n = 1:1000
    n
end

In [ ]:
@manipulate for n=1:20
    [i*j for i=1:n, j=1:n]
end

We use a double `for` loop to get a double slider!

In [ ]:
@manipulate for n=3:10, i=1:9
   A = fill(0, n, n)
   A[1:3, 1:3] = i    # fill a sub-block
A
end

# Functions

Julia is built around functions: all "commands" or "operations" in Julia are functions:

In [ ]:
# verbose form:
function f(x)
    x^2
end

# one-line form:
f2(x) = x^2

# anonymous form:
f3 = x -> x^2;

In [ ]:
f(10)

Functions just work, as long as they make sense:

In [ ]:
f(rand(3, 3))

In [ ]:
function f(x, power=2) # default argument
    x^power
end

In [ ]:
f(7)

In [ ]:
f(10,3)

Let's define a function to insert a block in a matrix:

In [14]:
function insert_block(A, i, j, what=7)
    B = A[:,:]        # B is a copy of A       
    B[i:i+2, j:j+2] = fill(what, 3, 3)
    
    return B          # the `return` keyword is optional
end

insert_block (generic function with 2 methods)

In [15]:
A = fill(0, 9, 9)
insert_block(A, 3, 5)  # this returns the new matrix

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [16]:
A = fill(0, 9, 9)
insert_block(A, 3, 5, 2)  # Use 2 instead of 7

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

We can move the block around:

In [17]:
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

# Strings

Julia can manipulate strings easily:

In [18]:
S = "Hello"

"Hello"

In [19]:
replace(S, "H", "J")

"Jello"

In [20]:
a = 3

3

In [21]:
string(S, " ", S, " ", "Julia; a = ", a)  # build a string by concatenating things

"Hello Hello Julia; a = 3"

More about strings: <a href="http://docs.julialang.org/en/stable/manual/strings/"> Julia Doc on Strings </a>

Functions in Julia try to be **generic**, i.e. to work with as many kinds of object as possible:

In [22]:
A = fill("Julia", 5, 5)

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

Julia allows us to display objects in different ways. For example, the following code displays a matrix of strings
in the notebook using an HTML representation:

In [23]:
function Base.show{T<:String}(io::IO, ::MIME"text/html", M::Matrix{T}) 
    max_length = maximum(length.(M))
    dv="<div style='display:flex;flex-direction:row'>"
    print(io, dv*join([join("<div style='width:40px; text-align:center'>".*M[i,:].*"</div>", " ") for i in 1:size(M, 1)]
            , "</div>$dv")*"</div>")
end

In [24]:
A

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

In [25]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

Let's use the **same code**, but now with strings:

In [27]:
A = fill("Julia", 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "[FUN]")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [28]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "π")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [29]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "♡")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [30]:
airplane = "✈"
alien = "👽"
rand([airplane, alien], 5, 5)

5×5 Array{String,2}:
 "👽"  "✈"  "👽"  "✈"  "✈"
 "✈"  "✈"  "👽"  "👽"  "✈"
 "👽"  "✈"  "✈"  "✈"  "👽"
 "✈"  "👽"  "👽"  "👽"  "👽"
 "👽"  "✈"  "✈"  "👽"  "👽"

In [31]:
A = fill(airplane, 9, 9)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, alien)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

9×9 Array{String,2}:
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"

# Colors

The `Colors` package provides objects representing colours:

In [32]:
using Colors

In [33]:
distinguishable_colors(12)

In [34]:
@manipulate for n = 1:80
    distinguishable_colors(n)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(40, nactions=1),"n",40,"40",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(68=>"68",2=>"2",11=>"11",39=>"39",46=>"46",25=>"25",55=>"55",42=>"42",29=>"29",58=>"58"…)),Any[],Any[],true,"horizontal")

In [35]:
colors = distinguishable_colors(100)


In [36]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

What happens if we use colours instead?

In [37]:
A = fill(colors[1], 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, colors[4])
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

In [38]:
# Exercise: Create Tetris Pieces, have them fall from the top